require:
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - tmp/**/*
    - lib/tasks/*
    - bin/*
    - rgloader/*
    - db/*
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 40
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/routes.rb

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  Exclude:
    - db/schema.rb

Style/IfUnlessModifier:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
