language: ruby
os: linux
dist: focal

rvm: 3.0.1

env:
  global:
    - PATH=/snap/bin:$PATH

cache: bundler

before_install:
  - "gem install bundler -v 2.1.4"
  - "curl https://storage.googleapis.com/travis-ci-misc/p4api-glibc2.3-openssl1.1.1.tgz | tar xz"
  - "bundle config --global build.p4ruby --with-p4api_dir=$PWD/p4api-2020.1.2187281"

jobs:
  include:
    - stage: "rubocop"
      script: bundle exec rubocop
    - stage: "rspec"
      script: bundle exec rspec
      before_script:
        - "RAILS_ENV=test bundle exec rake db:create"
      services:
        - redis
